# =========================
# Kitty Configuration
# Migrated from Alacritty
# Tema: Catppuccin Mocha
# =========================

# ---------
# Font
# ---------
# font_family      D2CodingLigature Nerd Font
# bold_font        D2CodingLigature Nerd Font Bold
# italic_font      D2CodingLigature Nerd Font
# bold_italic_font D2CodingLigature Nerd Font
font_size 15.0
disable_ligatures never

# ---------
# Cursor
# ---------
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# ---------
# Scrollback
# ---------
scrollback_lines 10000
wheel_scroll_multiplier 3.0
touch_scroll_multiplier 3.0

# ---------
# Mouse
# ---------
mouse_hide_wait 3.0

# ---------
# Window
# ---------
remember_window_size  no
initial_window_width  120c
initial_window_height 34c
window_padding_width 10
background_opacity 0.95
background_blur 1
macos_titlebar_color background
dynamic_background_opacity yes

# ---------
# Shell
# ---------
shell /bin/zsh --login

# ---------
# Keyboard Shortcuts
# ---------
map cmd+v paste_from_clipboard
map cmd+c copy_to_clipboard
map cmd+n new_os_window

# ---------
# Performance / Debug
# ---------
repaint_delay 10
input_delay 3
sync_to_monitor yes

# ---------
# Theme
# ---------
include current-theme.conf


# BEGIN_KITTY_FONTS
font_family      family="D2CodingLigature Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS